### ISSUE TITLE
Unlocked Galaxy S9 Plus Support

### ISSUE THREAD

**Issue by OsamaNasser** [fusionjack/Adhell3#13]
I was using SABS before and it was working perfectly.
I made a reset and it's not working anymore, now I'm using adhell3 and ad still appears on every app.
I'm using the default list and mmotti list.
I checked the report and it contains records from the app, however the ads still appear in this apps.

**Comment by OsamaNasser** [comment]
thanks, this will be great.
test adhell3 on your device and give us a feedback.

**Comment by Croshadow123** [comment]
I am getting some ads in Facebook Messenger that i need i can hide. Need sometime for check more of the apps.

I am sad that there is no way to block youtube ads.. in last couple weeks they got out of control.. toooo many i have now and there was time where i dindt get even one in couple of months

**Comment by Mike-BITW** [comment]
You can blacklist **graph.facebook.com** to block a few ads, but then it might interfere with other things you do with Facebook. Maybe switch to **Messenger Lite**, which has the same functionality but fewer unwanted content?

Depending on your configuration, you might find that accessing YouTube from your browser works better than using a dedicated app, but since both Facebook and YouTube rely on pushing ads to their viewers, you won't win that fight unless you quit using those services. ;)

**Comment by Croshadow123** [comment]
Does Adhell3 block very good ads on Samsung Internet Browser? Because i try without an additional adblocker and dindt work so well.

**Comment by Mike-BITW** [comment]
AdHell3 doesn't block anything, it simply allows you to select domains that you wish to block.  If your Samsung Internet Browser doesn't  allow blocking, there's nothing AdHell can do about that, but make sure you don't use your Browser's VPN option.  Switching to another browser may be a worthwhile consideration.

**Comment by Croshadow123** [comment]
I installed Adguard for Samsung Internet Browser and now is all okay. I dont think the browser has VPN option.

**Comment by fusionjack** [comment]
@OsamaNasser: if you see that some domains are blocked in the reported blocked domains, then the ads are blocked by knox firewall.
if you still see the ads, it might be that:
* there are some domains that are not in the default host list which you need to add them in the blacklist manually or
* the blocked ads are cached. in this case, try to reboot your phone.

@Croshadow123: 
* you can block **graph.facebook.com** globally, then whitelist it only for facebook messenger. see the README or the hint in the whitelist URL section.
* if you still see ads in samsung browser, this means that there are some domains that are not in the host list. on desktop, you can try to install adguard and open the website. check which domains are blocked by adguard. in adhell, check them in "show blocked urls" whether those domains are in the list and eventually, add them in the blacklist.
adguard or similiar browser's ads blocker have ability to hide html elements or frames which adhell cannot do.

**Comment by Mike-BITW** [comment]
I checked on the Samsung Internet Browser which I never use on my Note 8 (6.4.10.5), and it seems to use the Chrome-style Async DNS (the Port 53 thing).  I'm not sure all versions do.

**Comment by fusionjack** [comment]
i don't think that samsung internet browser uses chrome style dns.
the ads in samsung internet browser are blocked like others. i saw them in the report blocked domains.
if you see ads there, then the ads domain is not in the host list.

**Comment by fusionjack** [comment]
@OsamaNasser:
No, the key and package name have nothing to do with this behavior. It might be possible that on later Knox version, Samsung did change something.
Try to check adhell_log.txt on internal storage. Check the result of adding rules. There might be a hint there.
To make sure that the log contains the current one:
* Close all apps (so that no app is holding a lock to adhell_log.txt file)
* Turn off and then turn on Adhell
* Check adhell_log.txt on internal storage. You can post the log here and I'll take a look.

**Comment by OsamaNasser** [comment]
@fusionjack 
Here is what I found in the log file

![screenshot_20180403-201430](https://user-images.githubusercontent.com/37955439/38264526-e7d0d822-377b-11e8-98b2-dea2b936b24a.jpg)

**Comment by fusionjack** [comment]
the log looks ok. in which app you still see ads? how about in browser?

**Comment by OsamaNasser** [comment]
the browser is ok, no ads 
the ads come when I use "Super backup" (https://play.google.com/store/apps/details?id=com.idea.backup.smscontacts)

**Comment by fusionjack** [comment]
the ads of super backup app is mostly from graph.facebook.com. try to add it manually and then turn off/on adhell.
mine is blocked because i added it manually.
https://imgur.com/a/YqNKo

**Comment by fusionjack** [comment]
yeah, i also noticed that. it is an embedded ads.
ok then, i can close this issue.
