### ISSUE TITLE
Intermediary file manifest.xml, package isn't set correctly

### ISSUE THREAD

**Issue by JSalazarII** [fusionjack/Adhell3#2]
When attempting to build, as is, in the most recent version of android studio (version 3.1, JRE 1.8.0_152), the manifest.xml intermediary file does not have a proper "package" member of the "manifest" tag in manifest.xml. package is set to "com."

**Comment by fusionjack** [comment]
Yes, I did that intentionally so that any users who want to build, need to set their own package name, not by using the default one :).
Just set a random package name or a package name that you can remember because you can then update your app without reinstalling it again. Set it at _applicationId_ in _app/build.gradle_
I'll write "how-to-build" in the README soon.

**Comment by herexf** [comment]
Hi there

Are you going to replace the following? thanks.

testComplie -> testImplementation
complie -> implementation
provided -> compileOnly

**Comment by fusionjack** [comment]
@herexf: Done.
@JSalazarII: There is now "how-to-build" in the README.

**Comment by herexf** [comment]
Thanks

I can generate the debug apk but cannot generate release apk, not big issue, just for your information

Cheers

Lint found fatal errors while assembling a release target.

To proceed, either fix the issues identified by lint, or modify your build script as follows:
...
android {
    lintOptions {
        checkReleaseBuilds false
        // Or, if you prefer, you can continue to check for errors in release builds,
        // but continue the build even when errors are found:
        abortOnError false
    }
}

**Comment by fusionjack** [comment]
probably because of some inconsistent translation. i'll check it later
